[build]
  base = ""
  publish = "public"
  functions = "netlify/functions"
  command = "npm install --prefix netlify/functions"

[[redirects]]
  from = "/api/share/*"
  to = "/.netlify/functions/share?code=:splat"
  status = 200

[[redirects]]
  from = "/api/share"
  to = "/.netlify/functions/share"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
